### ISSUE TITLE
Close window of task button under mouse doesn't work in Windows 10

### ISSUE THREAD

**Issue by letmeindude** [7plus/7plus#430]
Will there be a fix or Windows 10 is too much work?

Thank you.

**Comment by ChrisS85** [comment]
From a quick look it seems like Microsoft doesn#t expose the usual control classes from Win32 API anymore, likely because it's written in a newer Framework. So it would mean atleast more research and some implementation effort, if possible at all. If anyone can point me in the right direction I may have a go at it though.

In the meantime, you can middle click on the preview windows that pop up over the button itself to close them.

**Comment by ChrisS85** [comment]
I found some motivation to fix this and a couple of other things (file size info and free disk space in explorer, some (but not all) issues with explorer tabs, Accessor open delay).
